version: "3.8"

services:
  linker:
    image: snltty/linker-musl
    container_name: linker
    privileged: true
    network_mode: host
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - "/$TRIM_APPDEST_VOL/@appshare/linker-docker/configs:/app/configs"
      - "/$TRIM_APPDEST_VOL/@appshare/linker-docker/logs:/app/logs"
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - SNLTTY_LINKER_IS_FNOS=linker