name: Sponsor

on:
  workflow_dispatch:


jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create dist directory
        run: mkdir dist

      - name: Run afdian-sponsor action
        uses: Sn0wo2/afdian-sponsor@v1
        env:
          AFDIAN_USER_ID: ${{ secrets.AFDIAN_USER_ID }}
          AFDIAN_API_TOKEN: ${{ secrets.AFDIAN_API_TOKEN }}
          AFDIAN_OUTPUT: "./dist/afdian-sponsor.svg"
          AFDIAN_TOTAL_SPONSORS: 100
          AFDIAN_AVATAR_SIZE: 300
          AFDIAN_MARGIN: 20
          AFDIAN_AVATARS_PER_ROW: 12
          AFDIAN_ACTIVE_SPONSOR_OPACITY: 1
          AFDIAN_EXPIRED_SPONSOR_OPACITY: 0.7
          AFDIAN_FONTSIZE_SCALE: 8
          AFDIAN_PADDINGX_SCALE: 0
          AFDIAN_PADDINGY_SCALE: 0

      - name: Push afdian-sponsor-svg to the sponsor branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: sponsor
          build_dir: dist
          commit_message: "ci(sponsor): deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
